### http://wiki.ros.org/amcl#Parameters
### There are three categories of ROS Parameters that can be used to configure the amcl node: 
### overall filter, laser model, and odometery model.

## Overall filter parameters

min_particles: 1000 #(int, default: 100) Minimum allowed number of particles.
#max_particles: #(int, default: 5000) Maximum allowed number of particles.

# In the project, you should set the position to [0, 0]. Feel free to play around with the mean yaw value.
initial_pose_x: 0 #(double, default: 0.0 meters) Initial pose mean (x), used to initialize filter with Gaussian distribution.
initial_pose_y: 0 #(double, default: 0.0 meters) Initial pose mean (y), used to initialize filter with Gaussian distribution.
initial_pose_a: 0 #(double, default: 0.0 radians) Initial pose mean (yaw), used to initialize filter with Gaussian distribution.
#initial_cov_xx #(double, default: 0.5*0.5 meters) Initial pose covariance (x*x), used to initialize filter with Gaussian distribution.
#initial_cov_yy #(double, default: 0.5*0.5 meters) Initial pose covariance (y*y), used to initialize filter with Gaussian distribution.
#initial_cov_aa #(double, default: (π/12)*(π/12) radian) Initial pose covariance (yaw*yaw), used to initialize filter with Gaussian distribution.

# amcl relies on incoming laser scans. 
# Upon receiving a scan, it checks the values for update_min_a and update_min_d and compares to how far the robot has moved. Based on this comparison it decides whether or not to perform a filter update or to discard the scan data. Discarding data could result in poorer localization results, and too many frequent filter updates for a fast moving robot could also cause computational problems.
update_min_d: 0.1 #(double, default: 0.2 meters) Translational movement required before performing a filter update.
update_min_a: 0.314 #(double, default: π/6.0 radians) Rotational movement required before performing a filter update.

#kld_err #(double, default: 0.01) Maximum error between the true distribution and the estimated distribution.
#kld_z #(double, default: 0.99) Upper standard normal quantile for (1 - p), where p is the probability that the error on the estimated distrubition will be less than kld_err.

#resample_interval: 1 #(int, default: 2) Number of filter updates required before resampling.
transform_tolerance: 0.5 #(double, default: 0.1 seconds) Time with which to post-date the transform that is published, to indicate that this transform is valid into the future.
recovery_alpha_slow: 0.001 #(double, default: 0.0 (disabled)) Exponential decay rate for the slow average weight filter, used in deciding when to recover by adding random poses. A good value might be 0.001.
recovery_alpha_fast: 0.1 #(double, default: 0.0 (disabled)) Exponential decay rate for the fast average weight filter, used in deciding when to recover by adding random poses. A good value might be 0.1.


#gui_publish_rate #(double, default: -1.0 Hz) Maximum rate (Hz) at which scans and paths are published for visualization, -1.0 to disable.
#save_pose_rate #(double, default: 0.5 Hz) Maximum rate (Hz) at which to store the last estimated pose and covariance to the parameter server, in the variables ~initial_pose_* and ~initial_cov_*. This saved pose will be used on subsequent runs to initialize the filter. -1.0 to disable.
use_map_topic: true #(bool, default: false) When set to true, AMCL will subscribe to the map topic rather than making a service call to receive its map. New in navigation 1.4.2
#first_map_only #(bool, default: false) When set to true, AMCL will only use the first map it subscribes to, rather than updating each time a new one is received. New in navigation 1.4.2



## Laser model parameters
## Note that whichever mixture weights are in use should sum to 1. The beam model uses all 4: z_hit, z_short, z_max, and z_rand. The likelihood_field model uses only 2: z_hit and z_rand.

#laser_model_type: "likelihood_field" #(string, default: "likelihood_field") Which model to use, either beam, likelihood_field, or likelihood_field_prob (same as likelihood_field but incorporates the beamskip feature, if enabled).
#laser_min_range: -1.0 #(double, default: -1.0) Minimum scan range to be considered; -1.0 will cause the laser's reported minimum range to be used.
#laser_max_range: -1.0 #(double, default: -1.0) Maximum scan range to be considered; -1.0 will cause the laser's reported maximum range to be used.
#laser_max_beams: 30 #(int, default: 30) How many evenly-spaced beams in each scan to be used when updating the filter.

#laser_z_hit: 0.95 #(double, default: 0.95) Mixture weight for the z_hit part of the model.
#laser_z_short: 0.1 #(double, default: 0.1) Mixture weight for the z_short part of the model.
#laser_z_max: 0.05 #(double, default: 0.05) Mixture weight for the z_max part of the model.
#laser_z_rand: 0.05 #(double, default: 0.05) Mixture weight for the z_rand part of the model.
#laser_sigma_hit: 0.2 #(double, default: 0.2 meters) Standard deviation for Gaussian model used in z_hit part of the model.
#laser_lambda_short: 0.1 #(double, default: 0.1) Exponential decay parameter for z_short part of model.
#laser_likelihood_max_dist: 2.0 #(double, default: 2.0 meters) Maximum distance to do obstacle inflation on map, for use in likelihood_field model.



## Odometry model parameters

odom_frame_id: "odom" #(string, default: "odom") Which frame to use for odometry.
base_frame_id: "robot_footprint" #(string, default: "base_link") Which frame to use for the robot base
global_frame_id: "map" #(string, default: "map") The name of the coordinate frame published by the localization system
#tf_broadcast: true #(bool, default: true) Set this to false to prevent amcl from publishing the transform between the global frame and the odometry frame.

## If ~odom_model_type is "diff" then we use the sample_motion_model_odometry algorithm from Probabilistic Robotics, p136; this model uses the noise parameters odom_alpha_1 through odom_alpha4, as defined in the book.
## If ~odom_model_type is "omni" then we use a custom model for an omni-directional base, which uses odom_alpha_1 through odom_alpha_5. The meaning of the first four parameters is similar to that for the "diff" model. The fifth parameter capture the tendency of the robot to translate (without rotating) perpendicular to the observed direction of travel.
## A bug was found and fixed. But fixing the old models would have changed or broken the localisation of already tuned robot systems, so the new fixed odometry models were added as new types "diff-corrected" and "omni-corrected". The default settings of the odom_alpha parameters only fit the old models, for the new model these values probably need to be a lot smaller, see http://answers.ros.org/question/227811/tuning-amcls-diff-corrected-and-omni-corrected-odom-models/.
# Here we are working with a differential drive mobile robot, 
odom_model_type: "diff-corrected" #(string, default: "diff") Which model to use, either "diff", "omni", "diff-corrected" or "omni-corrected".
odom_alpha1: 0.1 #(double, default: 0.2) Specifies the expected noise in odometry's rotation estimate from the rotational component of the robot's motion.
odom_alpha2: 0.1 #(double, default: 0.2) Specifies the expected noise in odometry's rotation estimate from translational component of the robot's motion.
odom_alpha3: 0.1 #(double, default: 0.2) Specifies the expected noise in odometry's translation estimate from the translational component of the robot's motion.
odom_alpha4: 0.1 #(double, default: 0.2) Specifies the expected noise in odometry's translation estimate from the rotational component of the robot's motion.
#odom_alpha5: #(double, default: 0.2) Translation-related noise parameter (only used if model is "omni").


