# http://wiki.ros.org/costmap_2d#Coordinate_frame_and_tf_parameters
map_type: costmap

#These parameters set thresholds on obstacle information put into the costmap. 
obstacle_range: 3.0 #determines the maximum range sensor reading that will result in an obstacle being put into the costmap. 
raytrace_range: 3.0 #determines the range to which we will raytrace freespace given a sensor reading.

robot_radius: 0.3
inflation_radius: 0.6

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}

